### ISSUE TITLE
fix logging

### ISSUE THREAD

**Issue by philsmart** [philsmart/raptor-harvest#12]
Everything is going to /var/log/raptor-harvest.log with no rotation (and its the wrong location)

**Comment by philsmart** [comment]
make it the same as the raptor-harvest config

**Comment by rhyssmith** [comment]
Is it?

### Logging configuration
logging.config=config/logback.xml
logging.file=/opt/raptor/harvest/logs/raptor-harvest-process.log

**Comment by philsmart** [comment]
although that is also duplicating the log file

**Comment by rhyssmith** [comment]
Agree that we need to sort rotation though

**Comment by philsmart** [comment]
yeah, it seems to be doing both, is it not for you?

**Comment by philsmart** [comment]
hang on, I have logged this on the harvest, needs to be on the server
