### ISSUE TITLE
Shibboleth v2 vs v3 logging formats

### ISSUE THREAD

**Issue by rhyssmith** [philsmart/raptor-harvest#8]
We should probably split out v2 vs v3 parsing, as it turns out the log formats are actually slightly different. So we should have the v3 as the default for raptor-harvest, but have a (commented out) v2 option as well.

v3 default Log Format:
```
%T|%b|%I|%SP|%P|%IDP|%bb|%III|%u|%ac|%attr|%n|%i|
```

Which according to https://wiki.shibboleth.net/confluence/display/IDP30/AuditLoggingConfiguration corresponds to:
```
Timestamp | Inbound Binding | Inbound Message ID | SP Entity ID | Profile ID | IdP Entity ID | Outbound Binding | Outbound Message ID | Username | Authentication Context | Attribute List | NameID Value | Assertion ID
```

Of those, I think we should parse them all but blank some of the IDs - i.e. Inbound Message ID, outbound message ID, Assertion ID. Keep the rest. Not sure about NameID Value, might be useful. Have to think about that...

v2 parsing will be as we had it before, because that was correct for v2.

For v3, we can pick up the IdP EntityID from the log file, so we don't need to specify that in the config. For v2 (and other systems like FreeRADIUS where we don't get the local EntityID/realm/etc) we'll still need to be able to specify that in the harvest config.

**Comment by philsmart** [comment]
Created a new v3 parser. Not entirely sure (other than IdPEntity ID) what the issue was before using the combined v2/v3 parser? the formats seems similar/identitcal otherwise.

**Comment by philsmart** [comment]
Also, I realise the IdP entity ID is now in the IDP logs, but that will always be the same? so we could just set it from the properties file like we do for V2 anyway?

**Comment by rhyssmith** [comment]
Only worth doing a separate v3 parser if it parses the idp entity id. It just means there's one less thing to configure on the client.

**Comment by philsmart** [comment]
ok fine.

**Comment by philsmart** [comment]
now supports both
